application: i-mposter 
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: imposter.wsgi.application

libraries:
- name: django
  version: "1.4"
- name: PIL
  version: "latest"
